Cleaned up build system of incorporated libshout.
Improved env-up script.

diff --git a/env-up b/env-up
--- a/env-up
+++ b/env-up
@@ -1,5 +1,19 @@
 #!/bin/bash
 
+function missing {
+	echo "$1, is missing - please install it and try again"
+	exit 1
+}
+
+function check {
+	for i in $* ; do
+		which $i > /dev/null || missing $i
+	done
+}
+
+check autoreconf libtool
+
+
 echo "remaking missing files in build environment"
 
 # Directory exists in git source only.
@@ -9,9 +23,5 @@ if [ -d docsrc ]; then
   cd ..
 fi
 
-cd libshout
 autoreconf -ifs
-# Recreates shout-config.in. Returns an error code.
-./configure >/dev/null 2>&1 || /bin/true
-cd ..
-autoreconf -ifs
+
